### ISSUE TITLE
Compilation failure on latest rust nightly

### ISSUE THREAD

**Issue by rossmuir** [mlalic/solicit#13]
https://travis-ci.org/mlalic/solicit/jobs/78031248

**Comment by mlalic** [comment]
Thanks for the quick reaction times! :)

I consider this to be some fairly strange behavior by `rustc`, as the `read_exact` feature is not turned on by the crate, so I wouldn't expect the compiler to even consider using the method. I've already asked about this under rust-lang/rust#28126.

In the short term, the method can be renamed to fix the conflict.

In the long term, the custom `read_exact` extension will no longer be necessary and should be removed in favor of the official `io::Read` method...

**Comment by rossmuir** [comment]
Thank you

**Comment by mlalic** [comment]
The new version (0.4.3) working around this is up on crates.io, by the way!

**Comment by bonifaido** [comment]
This was insanely fast! :+1:
