### ISSUE TITLE
Client::with_connector() panics with `Option::unwrap()` on a `None` value'`

### ISSUE THREAD

**Issue by tarrant** [mlalic/solicit#15]
This is related to issue #3 but with the async client instead of the SimpleClient.

Failing test case:

```
use http::client::CleartextConnector;
use client::Client;

pub fn reproduce() {
    let connector = CleartextConnector::new("google.com:8432"); // This is a second issue, port can't be loaded from this string.
    let client = Client::with_connector(connector);
}
```

**Comment by tarrant** [comment]
So I'm happy to submit a fix to this, but it requires a breaking change. I have to change `client::Client` to return a `Result` instead of an `Option`.

**Comment by mlalic** [comment]
I believe your fix addresses this sufficiently, so I'll close this now.

On the "second issue" you mention in the comment of the example, the `CleartextConnector` has another constructor: `CleartextConnector::with_port`, where you can pass in the port that it should contact.

**Comment by tarrant** [comment]
Correct. I found the `with_port`, the second issue I was alluding to was the fact that it didn't error that it was an invalid hostname. Should have been more clear.

Thanks!

**Comment by lucab** [comment]
I hit this today, several months after being fixed in master. Can we please have a new release tagged and crate uploaded?
