### ISSUE TITLE
SimpleClient::with_connector panics on unwrap

### ISSUE THREAD

**Issue by AKST** [mlalic/solicit#3]
[`SimpleClient::with_connector`][1] fails by [unwrap on None][2] instead of just returning an [`HttpError`][3] in a [`HttpResult`][4], this defeats the purpose of the result type. In my situation it could be happening because I'm testing with a server with a self signed certificate which I've done for testing purposes.

Failing without explicitly specifying this exception is probably a good thing for security reasons, but it would be great if it was an error that didn't panic.

[1]: https://mlalic.github.io/solicit/solicit/client/struct.SimpleClient.html#panics
[2]: https://github.com/mlalic/solicit/blob/master/src/client/simple.rs#L140
[3]: https://mlalic.github.io/solicit/solicit/http/enum.HttpError.html
[4]: https://mlalic.github.io/solicit/solicit/http/type.HttpResult.html

**Edit:** `::with_connection` -> `::with_connector`

**Comment by mlalic** [comment]
Thanks for the report!

Just to make sure: you mean the `SimpleClient::with_connector`, rather than `SimpleClient::with_connection` -- your links and text are a bit mismatched on that :)

Regardless, I agree that `with_connector` should not panic.

**Comment by AKST** [comment]
Oh right I meant `with_connector`!
