### ISSUE TITLE
HTTP footers

### ISSUE THREAD

**Issue by stepancheg** [mlalic/solicit#7]
`struct Response` does not have footers. Footers are needed to implement gRPC, which transmits request status in the footer header.

**Comment by stepancheg** [comment]
Doesn't matter, I can just inline server code.

**Comment by mlalic** [comment]
Hi @stepancheg,

I'm sorry, but these last few weeks I've been extremely busy and it's likely to be the case for at least another week or so, so I haven't had the time to work on this myself.

That said, I have two quick notes...

Firstly, what you call inlining the server code is actually what I'd expect would be the better course of action for you anyway. In fact, this is the kind of usage scenario that I primarily hoped to support.

The explicit goal of this particular library is to provide the low-level implementation of HTTP/2, not a full-fledged HTTP/2 server. The `SimpleServer` is just a simple example of how one might go about utilizing the core API for building a server. As such, it's severely limited to what a real high-performant HTTP/2 server should be like. For instance, it doesn't allow you to start streaming out a response piecemeal  as soon as you have a chunk, but requires that the whole thing is built up in memory and returned from the handler closure. This limitation, of course, is not present when you use the core API, which leaves the details of how/when certain parts of a message are sent completely up to the implementation. Another example would be that the `SimpleServer` uses just a raw TcpStream for its IO, which is far from what a really performant HTTP/2 server would want; the core API, however, doesn't limit you in any way on this and lends itself even to using an async event-loop style IO underneath...

This is not to say that a good generic server implementation is impossible on top of this library, just that for now it's not what *this* crate is supposed to provide... Hope it makes sense!

(Perhaps I should just completely remove the `SimpleServer` from here and move it to a separate crate to make it clear that this isn't meant to be a high-level solution for an HTTP/2 server...)

And secondly, while all the caveats of not aiming to support a full HTTP/2 server here still hold, the `DefaultStream` impl definitely still should provide a basic way to handle HTTP trailers out of the box, as it shouldn't be too complex -- when parsing the incoming message it should just make sure that it knows whether the received headers block is part of the headers or the trailer; when sending, don't close the stream on the last data chunk if there are trailers present and send them out using the same method as for headers (as they're both just a HEADERS + optional CONTINUATION frames on the framing layer).

As such, I'll open separate issues for the receiver and sender aspects of this issue. Of course, feel free to make a PR for either of those things, if that's something you feel like and have the time for.

Thanks for the issue and feel free to ping here again if there's a significant blocker for your work on gRPC, as I'd really like to help clear any blockers on that -- it'd be great to have a pure Rust implementation for it!
